import { afterEach, expect, test } from "bun:test";
import { Database } from "bun:sqlite";
import { EvmTradeWatchManager, type FrozenTradeVenue, type TradeWatchActivation, type TradeWatchAdapter, type TradeWatchExecution, type WatchedLeaderTrade } from "../server/evm-trade-watch";
import { evaluatePredicate, predicateHash, type GraphInputs } from "../cre/graph";
const A = (c:string) => `0x${c.repeat(40)}`;
const H = (c:string) => `0x${c.repeat(64)}`;
const venue:FrozenTradeVenue={network:"local",venueId:"pool",chainId:31337,genesisHash:H("1"),signer:A("1"),router:A("2"),factory:A("7"),pair:A("3"),token0:A("4"),token1:A("5"),routerCodeHash:H("2"),factoryCodeHash:H("4"),pairCodeHash:H("3"),headBlock:"10",headBlockHash:H("7")};
const config:TradeWatchActivation={activationId:"act",sessionId:"session",network:"local",venueId:"pool",leader:A("6"),startBlock:"next",tokenIn:venue.token0,tokenOut:venue.token1,proportionBps:5000,perTradeInputCapRaw:"40",cumulativeInputCapRaw:"60",slippageBps:100,maxTrades:2,intervalSeconds:15};
const trade=(h="a",block="11"):WatchedLeaderTrade=>({transactionHash:H(h),blockNumber:block,blockHash:H("7"),logIndex:0,leader:config.leader,router:venue.router,pair:venue.pair,tokenIn:venue.token0,tokenOut:venue.token1,amountInRaw:"100"});
const managers:EvmTradeWatchManager[]=[],dbs:Database[]=[];
afterEach(()=>{for(const m of managers.splice(0))m.close();for(const db of dbs.splice(0))db.close()});
function harness(overrides:Partial<TradeWatchAdapter>={},existingDb?:Database){
 const db=existingDb??new Database(":memory:");if(!existingDb)dbs.push(db);
 let now=Date.parse("2026-10-07T00:00:00Z"),head="10",trades:WatchedLeaderTrade[]=[],writes=0,scans=0;
 const execution=(input:Parameters<TradeWatchAdapter["execute"]>[0]):TradeWatchExecution=>({operationId:input.operationId,sourceTransactionHash:input.trade.transactionHash,chainId:venue.chainId,signer:venue.signer,tokenIn:input.trade.tokenIn,tokenOut:input.trade.tokenOut,amountInRaw:input.amountInRaw,status:"confirmed",transactionHash:H("8"),blockNumber:"12",amountOutRaw:"20"});
 const adapter:TradeWatchAdapter={freeze:async()=>structuredClone(venue),confirmedHead:async()=>head,blockHash:async()=>H("7"),scan:async(_v,_l,from,to)=>{scans++;return trades.filter(t=>BigInt(t.blockNumber)>=BigInt(from)&&BigInt(t.blockNumber)<=BigInt(to))},execute:async input=>{if(!await input.beforeBroadcast())return{...execution(input),status:"not-submitted",transactionHash:undefined};writes++;return execution(input)},reconcile:async({attempt})=>({...execution({venue,trade:attempt.source,operationId:attempt.operationId,amountInRaw:attempt.amountInRaw,slippageBps:100,beforeBroadcast:async()=>true}),status:"confirmed"}),...overrides};
 const manager=new EvmTradeWatchManager(db,adapter,{scheduling:false,now:()=>now});managers.push(manager);
 return{manager,db,adapter,advance:(s:number)=>{now+=s*1000},set:(h:string,t:WatchedLeaderTrade[])=>{head=h;trades=t},writes:()=>writes,scans:()=>scans,activate:(opts:Partial<TradeWatchActivation>={})=>manager.activate({...config,...opts}),now:()=>now};
}
test("explicit next baseline freezes identities and does not copy historical swaps",async()=>{const h=harness();h.set("10",[trade("a","10")]);const w=await h.activate();expect(w.nextBlock).toBe("11");w.venue.router=A("9");await h.manager.tick();expect(h.writes()).toBe(0);expect(h.manager.get(w.id).venue.router).toBe(venue.router);h.advance(15);h.set("11",[trade()]);await h.manager.tick();expect(h.writes()).toBe(1);expect(h.manager.attempts(w.id)[0]!.amountInRaw).toBe("40");expect(h.manager.get(w.id).nextBlock).toBe("12")});
test("activation retries dedup before reading a changing tip, conflicting authorization rejects",async()=>{let freezes=0;const h=harness({freeze:async()=>{freezes++;return{...venue,headBlock:String(10+freezes)}}});const [a,b]=await Promise.all([h.activate(),h.activate()]);expect(a.id).toBe(b.id);expect(freezes).toBe(1);expect((await h.activate()).nextBlock).toBe("12");await expect(h.activate({proportionBps:1000})).rejects.toThrow("reused");expect(h.manager.list()).toHaveLength(1)});
test("invalid targets, units, cadence and budgets cannot grant signing authority",async()=>{const h=harness();for(const opts of [{perTradeInputCapRaw:"61"},{perTradeInputCapRaw:"0"},{perTradeInputCapRaw:"01"},{intervalSeconds:14},{maxTrades:101},{tokenIn:venue.token1,tokenOut:venue.token1},{slippageBps:0},{proportionBps:10001}])await expect(h.activate(opts)).rejects.toThrow();const main=harness({freeze:async()=>({...venue,chainId:1})});await expect(main.activate()).rejects.toThrow("mainnet");expect(h.manager.list()).toHaveLength(0)});
test("one direction budget never combines token denominations",async()=>{const h=harness();const w=await h.activate();h.set("11",[{...trade(),tokenIn:venue.token1,tokenOut:venue.token0}]);await h.manager.tick();expect(h.writes()).toBe(0);expect(h.manager.get(w.id).reservedInputRaw).toBe("0");expect(h.manager.get(w.id).skippedEvents[0]!.reason).toContain("direction")});
test("count and cumulative input cap are reserved before broadcast and never exceeded",async()=>{const h=harness();const w=await h.activate();h.set("11",[trade("a"),trade("b")]);await h.manager.tick();expect(h.writes()).toBe(1);expect(h.manager.get(w.id).reservedTrades).toBe(1);expect(h.manager.get(w.id).reservedInputRaw).toBe("40");expect(h.manager.get(w.id).status).toBe("completed");expect(h.manager.attempts(w.id)).toHaveLength(1)});
test("max one attempt terminal status remains stopped even if more source swaps appear",async()=>{const h=harness();const w=await h.activate({maxTrades:1});h.set("11",[trade("a"),trade("b")]);await h.manager.tick();expect(h.manager.get(w.id).status).toBe("completed");h.advance(100);await h.manager.tick();expect(h.writes()).toBe(1)});
test("missed scan preserves cursor and deduplicates already settled source on retry",async()=>{let scans=0;const h=harness({scan:async()=>{scans++;if(scans===1)throw Error("RPC down");return[trade()]}});const w=await h.activate();h.set("11",[]);await h.manager.tick();expect(h.manager.get(w.id).nextBlock).toBe("11");expect(h.manager.get(w.id).lastError).toContain("RPC");h.advance(30);await h.manager.tick();expect(h.writes()).toBe(1);expect(h.manager.get(w.id).nextBlock).toBe("12")});
test("unknown outcome stops and read-only recovery never broadcasts another attempt",async()=>{let submitted=0,recoveries=0;const h=harness({execute:async()=>{submitted++;throw Error("Receipt lost")},reconcile:async({attempt})=>{recoveries++;return{operationId:attempt.operationId,sourceTransactionHash:attempt.source.transactionHash,chainId:venue.chainId,signer:venue.signer,tokenIn:config.tokenIn,tokenOut:config.tokenOut,amountInRaw:attempt.amountInRaw,status:"confirmed",transactionHash:H("8"),blockNumber:"12",amountOutRaw:"5"}}});const w=await h.activate();h.set("11",[trade()]);await h.manager.tick();expect(h.manager.get(w.id).status).toBe("uncertain");h.advance(99);await h.manager.tick();expect(submitted).toBe(1);await expect(h.activate({activationId:"other"})).rejects.toThrow("uncertain");const recovered=await h.manager.reconcile(w.id);expect(recovered.status).toBe("paused");expect(recoveries).toBe(1);expect(submitted).toBe(1);expect(h.manager.attempts(w.id)[0]!.status).toBe("confirmed")});
test("wrong signer and source in recovery remain uncertain",async()=>{const h=harness({execute:async()=>{throw Error("lost")},reconcile:async({attempt})=>({operationId:attempt.operationId,sourceTransactionHash:H("9"),chainId:31337,signer:venue.signer,tokenIn:config.tokenIn,tokenOut:config.tokenOut,amountInRaw:attempt.amountInRaw,status:"not-submitted"})});const w=await h.activate();h.set("11",[trade()]);await h.manager.tick();expect((await h.manager.reconcile(w.id)).status).toBe("uncertain");expect(h.manager.get(w.id).lastError).toContain("frozen")});
test("safe restart pauses watches; broadcast barrier survives restart as uncertain",async()=>{const h=harness();const w=await h.activate();h.manager.close();const restarted=harness({},h.db);expect(restarted.manager.get(w.id).status).toBe("paused");expect((await restarted.activate()).status).toBe("paused");await restarted.manager.tick();expect(restarted.writes()).toBe(0);const newWatch=await restarted.activate({activationId:"explicit-again"});newWatch.status="checking";newWatch.pendingAttemptId="reserved";h.db.query("UPDATE evm_trade_watches SET payload=? WHERE id=?").run(JSON.stringify(newWatch),newWatch.id);restarted.manager.close();const next=harness({},h.db);expect(next.manager.get(newWatch.id).status).toBe("uncertain");await expect(next.activate({activationId:"third"})).rejects.toThrow("uncertain")});
test("explicit stop during scan cancels future signing",async()=>{let release!:(t:WatchedLeaderTrade[])=>void;const h=harness({scan:async()=>new Promise(resolve=>{release=resolve})});const w=await h.activate();h.set("11",[]);const tick=h.manager.tick();await Bun.sleep(0);h.manager.stop(w.id);release([trade()]);await tick;expect(h.writes()).toBe(0);expect(h.manager.get(w.id).status).toBe("paused")});
test("concurrent ticks share one scan and malformed observations never sign",async()=>{let release!:(t:WatchedLeaderTrade[])=>void,calls=0;const h=harness({scan:async()=>{calls++;return new Promise(resolve=>{release=resolve})}});const w=await h.activate();h.set("11",[]);const tick=h.manager.tick();await Bun.sleep(0);await h.manager.tick();expect(calls).toBe(1);release([{...trade(),leader:A("9")}]);await tick;expect(h.writes()).toBe(0);expect(h.manager.get(w.id).status).toBe("active");expect(h.manager.get(w.id).nextBlock).toBe("11")});
const predicate={graph:{nodes:[{id:"a",kind:"price" as const,source:{type:"exchange-trade" as const,pair:"SOL-USD"}},{id:"b",kind:"compare" as const,input:"a",op:"<" as const,value:100}],root:"b"},exchangeMaxAgeSeconds:60};
function gate(h:ReturnType<typeof harness>,price:number){const inputs:GraphInputs={readings:{"exchange-trade:SOL-USD":{usd:price,observedAt:new Date(h.now()).toISOString()}},vaultPaused:null,exchangeMaxAgeSeconds:60};return{predicateHash:predicateHash(predicate.graph),inputs,result:evaluatePredicate(predicate.graph,inputs,h.now()),evaluatedAt:new Date(h.now()).toISOString()}}
test("false condition skips source permanently even if a failed later scan revisits block",async()=>{let price=200;const h=harness();h.adapter.evaluatePredicate=async()=>gate(h,price);const w=await h.activate({predicate});h.set("11",[trade()]);await h.manager.tick();expect(h.writes()).toBe(0);expect(h.manager.get(w.id).skippedEvents).toHaveLength(1);const state=h.manager.get(w.id);state.nextBlock="11";h.db.query("UPDATE evm_trade_watches SET payload=? WHERE id=?").run(JSON.stringify(state),w.id);price=50;h.advance(15);await h.manager.tick();expect(h.writes()).toBe(0);expect(h.manager.attempts(w.id)).toHaveLength(0)});
test("composed condition is freshly evaluated before actual handoff and archived on the attempt",async()=>{let calls=0;const h=harness();h.adapter.evaluatePredicate=async()=>gate(h,++calls===1?50:200);const w=await h.activate({predicate});h.set("11",[trade()]);await h.manager.tick();expect(calls).toBe(2);expect(h.writes()).toBe(0);expect(h.manager.attempts(w.id)[0]!.status).toBe("not-submitted");expect(h.manager.attempts(w.id)[0]!.gate!.result.decision).toBe("noop")});

test("a changed confirmed cursor anchor stops for explicit reorg review",async()=>{const h=harness({blockHash:async()=>H("9")});const w=await h.activate();h.set("11",[trade()]);await h.manager.tick();expect(h.manager.get(w.id).status).toBe("failed");expect(h.manager.get(w.id).nextBlock).toBe("11");expect(h.writes()).toBe(0);expect(h.manager.get(w.id).stopReason).toContain("reorg")});

test("a source aging beyond the frozen freshness cap blocks broadcast",async()=>{const h=harness();h.adapter.evaluatePredicate=async()=>{const g=gate(h,50);g.inputs.readings["exchange-trade:SOL-USD"]!.observedAt=new Date(h.now()-61000).toISOString();g.result=evaluatePredicate(predicate.graph,g.inputs,h.now());return g};const w=await h.activate({predicate});h.set("11",[trade()]);await h.manager.tick();expect(h.writes()).toBe(0);expect(h.manager.get(w.id).skippedEvents[0]!.gate!.result.blockedBy!.kind).toBe("source-freshness")});
test("rounded age display crossing a decimal does not invalidate genuine predicate evidence",async()=>{const h=harness();h.adapter.evaluatePredicate=async()=>{const g=gate(h,50);const at=h.now()-51;g.evaluatedAt=new Date(at).toISOString();g.result=evaluatePredicate(predicate.graph,g.inputs,at);return g};const w=await h.activate({predicate});h.set("11",[trade()]);await h.manager.tick();expect(h.writes()).toBe(1);expect(h.manager.attempts(w.id)[0]!.gate!.evaluatedAt).toBe(new Date(h.now()).toISOString())});
test("stopping during approval cancels the later guarded broadcast",async()=>{let beforeBroadcast!:()=>Promise<boolean>,release!:()=>void;const h=harness({execute:async input=>{beforeBroadcast=input.beforeBroadcast;await new Promise<void>(resolve=>{release=resolve});return{operationId:input.operationId,sourceTransactionHash:input.trade.transactionHash,chainId:venue.chainId,signer:venue.signer,tokenIn:input.trade.tokenIn,tokenOut:input.trade.tokenOut,amountInRaw:input.amountInRaw,status:await beforeBroadcast()?"uncertain":"not-submitted"}}});const w=await h.activate();h.set("11",[trade()]);const tick=h.manager.tick();await Bun.sleep(0);h.manager.stop(w.id);release();await tick;expect(h.manager.get(w.id).status).toBe("paused");expect(h.manager.get(w.id).pendingAttemptId).toBeUndefined();expect(h.manager.attempts(w.id)[0]!.status).toBe("not-submitted")});
