import { createPublicClient, createWalletClient, http, formatEther } from 'viem';
import { foundry } from 'viem/chains';
import { testnetAccount } from './testnet-wallet';
import { SUPPORTED_TESTNETS } from './deployment';
const chainId = Number(process.env.ORIGINS_TESTNET_CHAIN_ID || 84532);
const network = SUPPORTED_TESTNETS[chainId];
if (!network) throw new Error('Unsupported public testnet chain ID');
const rpcUrl = process.env.ORIGINS_TESTNET_RPC || network.rpcUrl;
const chain = {...foundry,id:chainId,name:network.name};
const client = createPublicClient({chain,transport:http(rpcUrl)});
if (await client.getChainId() !== chainId) throw new Error('RPC chain does not match chosen testnet');
const account = await testnetAccount(true);
const balance = await client.getBalance({address:account.address});
console.log(JSON.stringify({network:network.name,chainId,address:account.address,balanceEth:formatEther(balance)}));
if (process.argv.includes('--prepare')) process.exit(0);
if (balance === 0n) throw new Error('Fresh task wallet needs testnet gas; no deployment was attempted');
const build = Bun.spawn(['forge','build','--root','contracts'],{stdout:'inherit',stderr:'inherit'});
if (await build.exited !== 0) throw new Error('Contract compilation failed');
const wallet = createWalletClient({account,chain,transport:http(rpcUrl)});
const forwarder = await Bun.file('contracts/out/LocalRehearsalForwarder.sol/LocalRehearsalForwarder.json').json();
const forwarderHash = await wallet.deployContract({abi:forwarder.abi,bytecode:forwarder.bytecode.object});
const forwarderReceipt = await client.waitForTransactionReceipt({hash:forwarderHash});
if (forwarderReceipt.status !== 'success' || !forwarderReceipt.contractAddress) throw new Error('Test forwarder deployment failed');
const vault = await Bun.file('contracts/out/GrantVault.sol/GrantVault.json').json();
const deploymentHash = await wallet.deployContract({abi:vault.abi,bytecode:vault.bytecode.object,args:[forwarderReceipt.contractAddress,120n]});
const receipt = await client.waitForTransactionReceipt({hash:deploymentHash});
if (receipt.status !== 'success' || !receipt.contractAddress) throw new Error('Vault deployment failed');
const deployment = {address:receipt.contractAddress,forwarder:forwarderReceipt.contractAddress,owner:account.address,chainId,rpcUrl,mode:'testnet-evm',name:network.name,explorerUrl:network.explorerUrl,deploymentHash,forwarderHash,blockNumber:Number(receipt.blockNumber),createdAt:new Date().toISOString()};
const path = process.env.DEPLOYMENT_FILE || '.data/deployment.testnet.json';
await Bun.write(path,JSON.stringify(deployment,null,2));
console.log(JSON.stringify({deploymentFile:path,...deployment},null,2));
